from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QSizePolicy,
    QVBoxLayout, QWidget)
from qfluentwidgets import (BodyLabel, ProgressBar, PushButton, StrongBodyLabel,
    SubtitleLabel)
class DownloadWidget(QFrame):
    def __init__(self, parent):
        super().__init__(parent=parent)
        self.setObjectName("DownloadWidget")
        Form = self
        Form.resize(861, 284)
        self.verticalLayout_2 = QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.title_label = SubtitleLabel(self.widget)
        self.title_label.setObjectName(u"title_label")
        self.title_label.setTextFormat(Qt.RichText)
        self.title_label.setWordWrap(True)
        self.verticalLayout.addWidget(self.title_label)
        self.channel_label = StrongBodyLabel(self.widget)
        self.channel_label.setObjectName(u"channel_label")
        self.verticalLayout.addWidget(self.channel_label)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_3 = QWidget(Form)
        self.widget_3.setObjectName(u"widget_3")
        self.horizontalLayout_2 = QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.status_label = StrongBodyLabel(self.widget_3)
        self.status_label.setObjectName(u"status_label")
        self.horizontalLayout_2.addWidget(self.status_label)
        self.format_label = BodyLabel(self.widget_3)
        self.format_label.setObjectName(u"format_label")
        self.horizontalLayout_2.addWidget(self.format_label)
        self.quality_label = BodyLabel(self.widget_3)
        self.quality_label.setObjectName(u"quality_label")
        self.horizontalLayout_2.addWidget(self.quality_label)
        self.verticalLayout_2.addWidget(self.widget_3, 0, Qt.AlignLeft)
        self.widget_2 = QWidget(Form)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout = QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.widget_4 = QWidget(self.widget_2)
        self.widget_4.setObjectName(u"widget_4")
        self.verticalLayout_3 = QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setSpacing(18)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.progress_label = BodyLabel(self.widget_4)
        self.progress_label.setObjectName(u"progress_label")
        self.verticalLayout_3.addWidget(self.progress_label, 0, Qt.AlignHCenter)
        self.progress_bar = ProgressBar(self.widget_4)
        self.progress_bar.setObjectName(u"progress_bar")
        self.progress_bar.setMinimumSize(QSize(0, 6))
        self.progress_bar.setValue(0)
        self.progress_bar.setTextVisible(True)
        self.verticalLayout_3.addWidget(self.progress_bar)
        self.horizontalLayout.addWidget(self.widget_4, 0, Qt.AlignVCenter)
        self.cancel_btn = PushButton(self.widget_2)
        self.cancel_btn.setObjectName(u"cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.pause_btn = PushButton(self.widget_2)
        self.pause_btn.setObjectName(u"pause_btn")
        self.horizontalLayout.addWidget(self.pause_btn)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Frame", None))
        self.title_label.setText(QCoreApplication.translate("Form", u" TWILIGHT OF THE GODS | Epic Dark Dramatic Music \u2013 Best Epic Heroic Orchestral Music ", None))
        self.channel_label.setText(QCoreApplication.translate("Form", u"by Epic Music VN", None))
        self.status_label.setText(QCoreApplication.translate("Form", u"Status: Download started...", None))
        self.format_label.setText(QCoreApplication.translate("Form", u"Format: Video/mp4", None))
        self.quality_label.setText(QCoreApplication.translate("Form", u"Quality: 1080p/Best Audio", None))
        self.progress_label.setText(QCoreApplication.translate("Form", u"0% / ?? MB - ??:?? left (0 MB/s)", None))
        self.cancel_btn.setText(QCoreApplication.translate("Form", u"Cancel", None))
        self.pause_btn.setText(QCoreApplication.translate("Form", u"Pause", None))