
from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
    QSize, Qt)
from PySide6.QtGui import (QIcon, QAction)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QCheckBox,
    QComboBox, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QLineEdit,
    QPushButton, QScrollArea, QSizePolicy,
    QStackedWidget, QTableWidgetItem, QVBoxLayout, QWidget, QMenuBar, QMenu, QSpacerItem)

from src.CustomWidgets.CustomTableWidget import CustomTableWidget
from superqt import QLabeledRangeSlider, QLabeledSlider

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1150, 550)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1150, 550))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        self.actionSearch_For_Updates = QAction(MainWindow)
        self.actionSearch_For_Updates.setObjectName(u"actionSearch_For_Updates")
        self.actionSearch_For_Updates.setEnabled(True)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout.setEnabled(True)
        self.actionShow_on_Github = QAction(MainWindow)
        self.actionShow_on_Github.setObjectName(u"actionShow_on_Github")
        self.actionShow_on_Github.setEnabled(True)
        self.actionShow_Changelog = QAction(MainWindow)
        self.actionShow_Changelog.setObjectName(u"actionShow_Changelog")
        self.actionShow_Changelog.setEnabled(True)
        self.actionSet_FFmpeg_Path = QAction(MainWindow)
        self.actionSet_FFmpeg_Path.setObjectName(u"actionSet_FFmpeg_Path")
        self.actionSet_FFmpeg_Path.setEnabled(True)
        self.actionDownload_FFmpeg = QAction(MainWindow)
        self.actionDownload_FFmpeg.setObjectName(u"actionDownload_FFmpeg")
        self.actionDownload_FFmpeg.setEnabled(True)
        self.actionUpdate_Yt_dlp = QAction(MainWindow)
        self.actionUpdate_Yt_dlp.setObjectName(u"actionUpdate_Yt_dlp")
        self.actionUpdate_Yt_dlp.setEnabled(True)
        self.actionAutomatic_Update_Check = QAction(MainWindow)
        self.actionAutomatic_Update_Check.setObjectName(u"actionAutomatic_Update_Check")
        self.actionAutomatic_Update_Check.setCheckable(True)
        self.actionAutomatic_Update_Check.setEnabled(True)
        icon = QIcon()
        icon.addFile(u"appdata/images/square.png", QSize(), QIcon.Selected, QIcon.Off)
        icon.addFile(u"appdata/images/check-square.png", QSize(), QIcon.Selected, QIcon.On)
        self.actionAutomatic_Update_Check.setIcon(icon)
        self.actionShow_Thumbnails = QAction(MainWindow)
        self.actionShow_Thumbnails.setObjectName(u"actionShow_Thumbnails")
        self.actionShow_Thumbnails.setCheckable(True)
        self.actionShow_Thumbnails.setEnabled(True)
        self.actionShow_Thumbnails.setIcon(icon)
        self.actionChange_Download_Folder = QAction(MainWindow)
        self.actionChange_Download_Folder.setObjectName(u"actionChange_Download_Folder")
        self.actionReveal_in_File_Explorer = QAction(MainWindow)
        self.actionReveal_in_File_Explorer.setObjectName(u"actionReveal_in_File_Explorer")
        self.actionDefault_Resolution = QAction(MainWindow)
        self.actionDefault_Resolution.setObjectName(u"actionDefault_Resolution")
        self.actionMaximum_Threads = QAction(MainWindow)
        self.actionMaximum_Threads.setObjectName(u"actionMaximum_Threads")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.main_frame = QFrame(self.centralwidget)
        self.main_frame.setObjectName(u"main_frame")
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setFrameShape(QFrame.NoFrame)
        self.main_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.sidebar = QFrame(self.main_frame)
        self.sidebar.setObjectName(u"sidebar")
        self.sidebar.setMaximumSize(QSize(70, 16777214))
        self.sidebar.setStyleSheet(u"")
        self.sidebar.setFrameShape(QFrame.NoFrame)
        self.sidebar.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.sidebar)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.sb_top_frame = QFrame(self.sidebar)
        self.sb_top_frame.setObjectName(u"sb_top_frame")
        self.sb_top_frame.setFrameShape(QFrame.NoFrame)
        self.sb_top_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.sb_top_frame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.toggle_sidebar_btn = QPushButton(self.sb_top_frame)
        self.toggle_sidebar_btn.setObjectName(u"toggle_sidebar_btn")
        icon1 = QIcon()
        icon1.addFile(u"appdata/images/menu.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_sidebar_btn.setIcon(icon1)
        self.toggle_sidebar_btn.setIconSize(QSize(45, 45))

        self.verticalLayout_5.addWidget(self.toggle_sidebar_btn)

        self.verticalSpacer = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_5.addItem(self.verticalSpacer)

        self.search_btn = QPushButton(self.sb_top_frame)
        self.search_btn.setObjectName(u"search_btn")
        self.search_btn.setMinimumSize(QSize(0, 50))
        icon2 = QIcon()
        icon2.addFile(u"appdata/images/search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.search_btn.setIcon(icon2)
        self.search_btn.setIconSize(QSize(45, 45))
        self.search_btn.setCheckable(True)
        self.search_btn.setAutoExclusive(True)

        self.verticalLayout_5.addWidget(self.search_btn)

        self.download_btn = QPushButton(self.sb_top_frame)
        self.download_btn.setObjectName(u"download_btn")
        self.download_btn.setEnabled(True)
        self.download_btn.setMinimumSize(QSize(0, 50))
        icon3 = QIcon()
        icon3.addFile(u"appdata/images/download.png", QSize(), QIcon.Normal, QIcon.Off)
        icon3.addFile(u"appdata/images/download-disabled.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.download_btn.setIcon(icon3)
        self.download_btn.setIconSize(QSize(45, 45))
        self.download_btn.setCheckable(True)
        self.download_btn.setAutoExclusive(True)

        self.verticalLayout_5.addWidget(self.download_btn)

        self.file_btn = QPushButton(self.sb_top_frame)
        self.file_btn.setObjectName(u"file_btn")
        self.file_btn.setMinimumSize(QSize(0, 50))
        icon4 = QIcon()
        icon4.addFile(u"appdata/images/explorer.png", QSize(), QIcon.Normal, QIcon.Off)
        self.file_btn.setIcon(icon4)
        self.file_btn.setIconSize(QSize(45, 45))
        self.file_btn.setCheckable(True)
        self.file_btn.setAutoExclusive(True)

        self.verticalLayout_5.addWidget(self.file_btn)


        self.verticalLayout_3.addWidget(self.sb_top_frame, 0, Qt.AlignTop)

        self.sb_bottom_frame = QFrame(self.sidebar)
        self.sb_bottom_frame.setObjectName(u"sb_bottom_frame")
        self.sb_bottom_frame.setFrameShape(QFrame.NoFrame)
        self.sb_bottom_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.sb_bottom_frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.exit_btn = QPushButton(self.sb_bottom_frame)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setMinimumSize(QSize(70, 50))
        icon5 = QIcon()
        icon5.addFile(u"appdata/images/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.exit_btn.setIcon(icon5)
        self.exit_btn.setIconSize(QSize(45, 45))

        self.verticalLayout_4.addWidget(self.exit_btn)


        self.verticalLayout_3.addWidget(self.sb_bottom_frame, 0, Qt.AlignBottom)


        self.horizontalLayout_2.addWidget(self.sidebar)

        self.frame_5 = QFrame(self.main_frame)
        self.frame_5.setObjectName(u"frame_5")
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.mainpages = QStackedWidget(self.frame_5)
        self.mainpages.setObjectName(u"mainpages")
        sizePolicy.setHeightForWidth(self.mainpages.sizePolicy().hasHeightForWidth())
        self.mainpages.setSizePolicy(sizePolicy)
        self.mpage1 = QWidget()
        self.mpage1.setObjectName(u"mpage1")
        sizePolicy.setHeightForWidth(self.mpage1.sizePolicy().hasHeightForWidth())
        self.mpage1.setSizePolicy(sizePolicy)
        self.verticalLayout_9 = QVBoxLayout(self.mpage1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.mpage1)
        self.frame.setObjectName(u"frame")
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setContentsMargins(25, 25, 25, 25)
        self.search_stack_widg = QStackedWidget(self.frame)
        self.search_stack_widg.setObjectName(u"search_stack_widg")
        sizePolicy.setHeightForWidth(self.search_stack_widg.sizePolicy().hasHeightForWidth())
        self.search_stack_widg.setSizePolicy(sizePolicy)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.verticalLayout_10 = QVBoxLayout(self.page)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.info_start_label = QLabel(self.page)
        self.info_start_label.setObjectName(u"info_start_label")
        self.info_start_label.setAlignment(Qt.AlignCenter)
        self.info_start_label.setWordWrap(False)

        self.verticalLayout_10.addWidget(self.info_start_label, 0, Qt.AlignHCenter|Qt.AlignTop)

        self.search_stack_widg.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setMinimumSize(QSize(0, 0))
        self.verticalLayout_12 = QVBoxLayout(self.page_2)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.page_2)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1026, 69))
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QSize(0, 0))
        self.gridLayout_2 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setSizeConstraint(QLayout.SetNoConstraint)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_12.addWidget(self.scrollArea, 0, Qt.AlignTop)

        self.search_stack_widg.addWidget(self.page_2)

        self.gridLayout.addWidget(self.search_stack_widg, 2, 0, 1, 1)

        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_11 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(10, 0, 10, 0)
        self.url_entry = QLineEdit(self.frame_3)
        self.url_entry.setObjectName(u"url_entry")
        self.url_entry.setEnabled(True)
        self.url_entry.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_11.addWidget(self.url_entry)

        self.searching_button = QPushButton(self.frame_3)
        self.searching_button.setObjectName(u"searching_button")
        self.searching_button.setEnabled(False)

        self.horizontalLayout_11.addWidget(self.searching_button)


        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)


        self.verticalLayout_9.addWidget(self.frame)

        self.mainpages.addWidget(self.mpage1)
        self.mpage2 = QWidget()
        self.mpage2.setObjectName(u"mpage2")
        self.verticalLayout_6 = QVBoxLayout(self.mpage2)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.download_1 = QFrame(self.mpage2)
        self.download_1.setObjectName(u"download_1")
        self.download_1.setFrameShape(QFrame.StyledPanel)
        self.download_1.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.download_1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.image_frame = QFrame(self.download_1)
        self.image_frame.setObjectName(u"image_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.image_frame.sizePolicy().hasHeightForWidth())
        self.image_frame.setSizePolicy(sizePolicy1)
        self.image_frame.setMinimumSize(QSize(480, 270))
        self.image_frame.setFrameShape(QFrame.StyledPanel)
        self.image_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.image_frame)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.image_label = QLabel(self.image_frame)
        self.image_label.setObjectName(u"image_label")
        sizePolicy1.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy1)
        self.image_label.setMinimumSize(QSize(480, 270))
        self.image_label.setMaximumSize(QSize(480, 270))
        self.image_label.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_9.addWidget(self.image_label)


        self.horizontalLayout_4.addWidget(self.image_frame)

        self.label_frame = QFrame(self.download_1)
        self.label_frame.setObjectName(u"label_frame")
        self.label_frame.setFrameShape(QFrame.StyledPanel)
        self.label_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.label_frame)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.name_label = QLabel(self.label_frame)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setWordWrap(True)

        self.verticalLayout_2.addWidget(self.name_label)

        self.artist_label = QLabel(self.label_frame)
        self.artist_label.setObjectName(u"artist_label")
        self.artist_label.setWordWrap(True)

        self.verticalLayout_2.addWidget(self.artist_label)

        self.date_label = QLabel(self.label_frame)
        self.date_label.setObjectName(u"date_label")

        self.verticalLayout_2.addWidget(self.date_label)

        self.duration_label = QLabel(self.label_frame)
        self.duration_label.setObjectName(u"duration_label")

        self.verticalLayout_2.addWidget(self.duration_label)


        self.horizontalLayout_4.addWidget(self.label_frame, 0, Qt.AlignTop)


        self.verticalLayout_6.addWidget(self.download_1)

        self.download_2 = QStackedWidget(self.mpage2)
        self.download_2.setObjectName(u"download_2")
        self.download_2.setFrameShape(QFrame.StyledPanel)
        self.download_2.setFrameShadow(QFrame.Raised)
        self.download_bar_page1 = QWidget()
        self.download_bar_page1.setObjectName(u"download_bar_page1")
        self.verticalLayout_7 = QVBoxLayout(self.download_bar_page1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.selection_frame = QFrame(self.download_bar_page1)
        self.selection_frame.setObjectName(u"selection_frame")
        self.selection_frame.setFrameShape(QFrame.StyledPanel)
        self.selection_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.selection_frame)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(300, 0, 300, 0)
        self.format_selection = QComboBox(self.selection_frame)
        self.format_selection.setObjectName(u"format_selection")

        self.horizontalLayout_5.addWidget(self.format_selection)

        self.resolution_selection = QComboBox(self.selection_frame)
        self.resolution_selection.setObjectName(u"resolution_selection")

        self.horizontalLayout_5.addWidget(self.resolution_selection)


        self.verticalLayout_7.addWidget(self.selection_frame)

        self.download_btn_frame = QFrame(self.download_bar_page1)
        self.download_btn_frame.setObjectName(u"download_btn_frame")
        self.download_btn_frame.setFrameShape(QFrame.StyledPanel)
        self.download_btn_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.download_btn_frame)
        self.horizontalLayout_6.setSpacing(25)
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.last_page_btn = QPushButton(self.download_btn_frame)
        self.last_page_btn.setObjectName(u"last_page_btn")

        self.horizontalLayout_6.addWidget(self.last_page_btn, 0, Qt.AlignLeft)

        self.download_button = QPushButton(self.download_btn_frame)
        self.download_button.setObjectName(u"download_button")

        self.horizontalLayout_6.addWidget(self.download_button)


        self.verticalLayout_7.addWidget(self.download_btn_frame, 0, Qt.AlignHCenter)

        self.download_2.addWidget(self.download_bar_page1)
        self.download_bar_page3 = QWidget()
        self.download_bar_page3.setObjectName(u"download_bar_page3")
        self.verticalLayout_8 = QVBoxLayout(self.download_bar_page3)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.info_range_slider_label = QLabel(self.download_bar_page3)
        self.info_range_slider_label.setObjectName(u"info_range_slider_label")
        self.info_range_slider_label.setMaximumSize(QSize(16777215, 30))
        self.info_range_slider_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_8.addWidget(self.info_range_slider_label)

        self.playlist_range_slider = QLabeledRangeSlider(self.download_bar_page3)
        self.playlist_range_slider.setObjectName(u"playlist_range_slider")
        sizePolicy.setHeightForWidth(self.playlist_range_slider.sizePolicy().hasHeightForWidth())
        self.playlist_range_slider.setSizePolicy(sizePolicy)
        self.playlist_range_slider.setMinimumSize(QSize(0, 20))
        self.playlist_range_slider.setMaximumSize(QSize(16777215, 80))
        self.playlist_range_slider.setOrientation(Qt.Horizontal)

        self.verticalLayout_8.addWidget(self.playlist_range_slider)

        self.next_page_btn = QPushButton(self.download_bar_page3)
        self.next_page_btn.setObjectName(u"next_page_btn")
        self.next_page_btn.setMinimumSize(QSize(150, 0))

        self.verticalLayout_8.addWidget(self.next_page_btn, 0, Qt.AlignHCenter)

        self.download_2.addWidget(self.download_bar_page3)

        self.verticalLayout_6.addWidget(self.download_2)

        self.mainpages.addWidget(self.mpage2)
        self.mpage4 = QWidget()
        self.mpage4.setObjectName(u"mpage4")
        self.verticalLayout_13 = QVBoxLayout(self.mpage4)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(15, 15, 15, 15)
        self.tableWidget = CustomTableWidget(self.mpage4)
        if (self.tableWidget.columnCount() < 6):
            self.tableWidget.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setFrameShape(QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QFrame.Sunken)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QAbstractItemView.EditKeyPressed)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableWidget.setTextElideMode(Qt.ElideRight)
        self.tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(Qt.SolidLine)
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(0)
        self.tableWidget.verticalHeader().setDefaultSectionSize(39)

        self.verticalLayout_13.addWidget(self.tableWidget)

        self.frame_2 = QFrame(self.mpage4)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.download_delete_btn = QPushButton(self.frame_2)
        self.download_delete_btn.setObjectName(u"download_delete_btn")
        self.download_delete_btn.setEnabled(False)

        self.horizontalLayout_8.addWidget(self.download_delete_btn)

        self.download_open_btn = QPushButton(self.frame_2)
        self.download_open_btn.setObjectName(u"download_open_btn")
        self.download_open_btn.setEnabled(False)

        self.horizontalLayout_8.addWidget(self.download_open_btn)

        self.download_download_btn = QPushButton(self.frame_2)
        self.download_download_btn.setObjectName(u"download_download_btn")
        self.download_download_btn.setEnabled(False)

        self.horizontalLayout_8.addWidget(self.download_download_btn)


        self.verticalLayout_13.addWidget(self.frame_2)

        self.mainpages.addWidget(self.mpage4)

        self.horizontalLayout_3.addWidget(self.mainpages)


        self.horizontalLayout_2.addWidget(self.frame_5)


        self.verticalLayout.addWidget(self.main_frame)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1150, 37))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuTools = QMenu(self.menuBar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuFile_2 = QMenu(self.menuBar)
        self.menuFile_2.setObjectName(u"menuFile_2")
        MainWindow.setMenuBar(self.menuBar)
        QWidget.setTabOrder(self.search_btn, self.download_btn)
        QWidget.setTabOrder(self.download_btn, self.exit_btn)
        QWidget.setTabOrder(self.exit_btn, self.resolution_selection)
        QWidget.setTabOrder(self.resolution_selection, self.last_page_btn)
        QWidget.setTabOrder(self.last_page_btn, self.download_button)
        QWidget.setTabOrder(self.download_button, self.format_selection)
        QWidget.setTabOrder(self.format_selection, self.scrollArea)

        self.menuBar.addAction(self.menuFile_2.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionAutomatic_Update_Check)
        self.menuFile.addAction(self.actionShow_Thumbnails)
        self.menuFile.addAction(self.actionDefault_Resolution)
        self.menuFile.addAction(self.actionMaximum_Threads)
        self.menuHelp.addAction(self.actionSearch_For_Updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionShow_on_Github)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionShow_Changelog)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionSet_FFmpeg_Path)
        self.menuTools.addAction(self.actionDownload_FFmpeg)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionUpdate_Yt_dlp)
        self.menuFile_2.addAction(self.actionChange_Download_Folder)
        self.menuFile_2.addAction(self.actionReveal_in_File_Explorer)

        self.retranslateUi(MainWindow)

        self.mainpages.setCurrentIndex(0)
        self.search_stack_widg.setCurrentIndex(1)
        self.download_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Youtube Downloader v1.3.0", None))
        self.actionSearch_For_Updates.setText(QCoreApplication.translate("MainWindow", u"Search for Updates", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionShow_on_Github.setText(QCoreApplication.translate("MainWindow", u"Show on Github", None))
        self.actionShow_Changelog.setText(QCoreApplication.translate("MainWindow", u"Show Changelog", None))
        self.actionSet_FFmpeg_Path.setText(QCoreApplication.translate("MainWindow", u"Set FFmpeg-Path", None))
        self.actionDownload_FFmpeg.setText(QCoreApplication.translate("MainWindow", u"Download FFmpeg", None))
        self.actionUpdate_Yt_dlp.setText(QCoreApplication.translate("MainWindow", u"Update Yt-dlp", None))
        self.actionAutomatic_Update_Check.setText(QCoreApplication.translate("MainWindow", u"Auto Update Check", None))
        self.actionShow_Thumbnails.setText(QCoreApplication.translate("MainWindow", u"Show Thumbnails", None))
        self.actionChange_Download_Folder.setText(QCoreApplication.translate("MainWindow", u"Change Download Folder", None))
        self.actionReveal_in_File_Explorer.setText(QCoreApplication.translate("MainWindow", u"Reveal in File Explorer", None))
        self.actionDefault_Resolution.setText(QCoreApplication.translate("MainWindow", u"Default Resolution", None))
        self.actionMaximum_Threads.setText(QCoreApplication.translate("MainWindow", u"Maximum Threads", None))
        self.toggle_sidebar_btn.setText("")
        self.search_btn.setText(QCoreApplication.translate("MainWindow", u"  Search", None))
        self.download_btn.setText(QCoreApplication.translate("MainWindow", u"  Download", None))
        self.file_btn.setText(QCoreApplication.translate("MainWindow", u"  Files", None))
        self.exit_btn.setText(QCoreApplication.translate("MainWindow", u"  Exit", None))
        self.info_start_label.setText("")
        self.url_entry.setText("")
        self.url_entry.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Insert Video or Playlist URL", None))
        self.searching_button.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.image_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail", None))
        self.name_label.setText("")
        self.artist_label.setText("")
        self.date_label.setText("")
        self.duration_label.setText("")
        self.last_page_btn.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.download_button.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.info_range_slider_label.setText("")
        self.next_page_btn.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Channel", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Video Name", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Format", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Resolution", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Progress", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"ETA", None));
        self.download_delete_btn.setText(QCoreApplication.translate("MainWindow", u"Delete File", None))
        self.download_open_btn.setText(QCoreApplication.translate("MainWindow", u"Open File", None))
        self.download_download_btn.setText(QCoreApplication.translate("MainWindow", u"Redownload File", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuFile_2.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

